server:
  session:
    timeout: 10000

spring:
  servlet:
    multipart:
      max-file-size: 1200MB
      max-request-size: 2000MB
  jpa:
    hibernate:
      generate-ddl: false
      ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
