const REQUEST_BUILD_INFO = 'REQUEST_BUILD_INFO'
const RECEIVE_BUILD_INFO = 'RECEIVE_BUILD_INFO'
const REQUEST_LOGGED_USER = 'REQUEST_LOGGED_USER'
const RECEIVE_LOGGED_USER = 'RECEIVE_LOGGED_USER'
const REQUEST_COMPONENTS = 'REQUEST_COMPONENTS'
const REQUEST_COMPONENT_VERSIONS = 'REQUEST_COMPONENT_VERSIONS'
const RECEIVE_COMPONENTS = 'RECEIVE_COMPONENTS'
const RECEIVE_COMPONENT_VERSIONS = 'RECEIVE_COMPONENT_VERSIONS'
const RECEIVE_COMPONENT_VERSIONS_ERROR = 'RECEIVE_COMPONENT_VERSIONS_ERROR'
const EXPAND_COMPONENT = 'EXPAND_COMPONENT'
const CLOSE_COMPONENT = 'CLOSE_COMPONENT'
const REQUEST_ARTIFACTS_LIST = 'REQUEST_ARTIFACTS_LIST'
const RECEIVE_ARTIFACTS_LIST = 'RECEIVE_ARTIFACTS_LIST'
const REQUEST_DOCUMENT_ARTIFACT = 'REQUEST_DOCUMENT_ARTIFACT'
const RECEIVE_DOCUMENT_ARTIFACT = 'RECEIVE_DOCUMENT_ARTIFACT'
const ERROR_OCCURED = 'ERROR_OCCURED'
const HIDE_ERROR = 'HIDE_ERROR'
const TOGGLE_RC = 'TOGGLE_RC'
const TOGGLE_ADMIN_MODE = 'TOGGLE_ADMIN_MODE'
const DELETE_ARTIFACT = 'DELETE_ARTIFACT'
const SUCCESS_DELETE_ARTIFACT = 'SUCCESS_DELETE_ARTIFACT'
const SHOW_CONFIRMATION = 'SHOW_CONFIRMATION'
const HIDE_CONFIRMATION = 'HIDE_CONFIRMATION'
const REQUEST_SEARCH = 'REQUEST_SEARCH'
const RECEIVE_SEARCH = 'RECEIVE_SEARCH'
const CHANGE_SEARCH_QUERY_VALID = 'CHANGE_SEARCH_QUERY_VALID'
const REQUEST_COMPONENT_MINOR_VERSIONS = 'REQUEST_COMPONENT_MINOR_VERSIONS'
const RECEIVE_COMPONENT_MINOR_VERSIONS = 'RECEIVE_COMPONENT_MINOR_VERSIONS'
const RECEIVE_COMPONENT_MINOR_VERSIONS_ERROR = 'RECEIVE_COMPONENT_MINOR_VERSIONS_ERROR'
const EXPAND_MINOR_VERSION = 'EXPAND_MINOR_VERSION'
const CLOSE_MINOR_VERSION = 'CLOSE_MINOR_VERSION'
const SELECT_VERSION = 'SELECT_VERSION'

export default {
    REQUEST_BUILD_INFO,
    RECEIVE_BUILD_INFO,
    REQUEST_LOGGED_USER,
    RECEIVE_LOGGED_USER,
    REQUEST_COMPONENTS,
    REQUEST_COMPONENT_VERSIONS,
    RECEIVE_COMPONENTS,
    RECEIVE_COMPONENT_VERSIONS_ERROR,
    RECEIVE_COMPONENT_VERSIONS,
    EXPAND_COMPONENT,
    CLOSE_COMPONENT,
    REQUEST_ARTIFACTS_LIST,
    RECEIVE_ARTIFACTS_LIST,
    REQUEST_DOCUMENT_ARTIFACT,
    RECEIVE_DOCUMENT_ARTIFACT,
    ERROR_OCCURED,
    HIDE_ERROR,
    TOGGLE_RC,
    TOGGLE_ADMIN_MODE,
    DELETE_ARTIFACT,
    SUCCESS_DELETE_ARTIFACT,
    SHOW_CONFIRMATION,
    HIDE_CONFIRMATION,
    REQUEST_SEARCH,
    RECEIVE_SEARCH,
    CHANGE_SEARCH_QUERY_VALID,
    REQUEST_COMPONENT_MINOR_VERSIONS,
    RECEIVE_COMPONENT_MINOR_VERSIONS,
    RECEIVE_COMPONENT_MINOR_VERSIONS_ERROR,
    EXPAND_MINOR_VERSION,
    CLOSE_MINOR_VERSION,
    SELECT_VERSION
}
