apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: artifactory-template

objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ${DEPLOYMENT_PREFIX}-artifactory-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2.5Gi
      volumeMode: Filesystem

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${DEPLOYMENT_PREFIX}-artifactory-config
    data:
      system.yaml: |
        shared:
          database:
            type: postgresql
            driver: org.postgresql.Driver
            url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}
            username: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
      artifactory.system.properties: |
        artifactory.allow.export.import.insecure.paths=true

  - apiVersion: v1
    kind: Pod
    metadata:
      name: ${DEPLOYMENT_PREFIX}-artifactory
      labels:
        app.kubernetes.io/name: ${DEPLOYMENT_PREFIX}-artifactory
    spec:
      restartPolicy: Never
      activeDeadlineSeconds: ${{ACTIVE_DEADLINE_SECONDS}}

      initContainers:
        - name: setup-artifactory-config
          image: releases-docker.jfrog.io/jfrog/artifactory-oss:${ARTIFACTORY_IMAGE_TAG}
          command:
            - sh
            - -c
            - |
              set -e
              echo "Initializing Artifactory configuration"
              mkdir -p /opt/jfrog/artifactory/var/etc/artifactory
              echo "Copying system.yaml"
              cp /tmp/system.yaml /opt/jfrog/artifactory/var/etc/system.yaml
              echo "Copying artifactory.system.properties"
              cp /tmp/artifactory.system.properties /opt/jfrog/artifactory/var/etc/artifactory/artifactory.system.properties
              chmod 666 /opt/jfrog/artifactory/var/etc/system.yaml
              chmod 666 /opt/jfrog/artifactory/var/etc/artifactory/artifactory.system.properties
          volumeMounts:
            - name: artifactory-data
              mountPath: /opt/jfrog/artifactory/var
            - name: artifactory-config
              mountPath: /tmp/system.yaml
              subPath: system.yaml
            - name: artifactory-config
              mountPath: /tmp/artifactory.system.properties
              subPath: artifactory.system.properties

      containers:
        - name: artifactory
          image: releases-docker.jfrog.io/jfrog/artifactory-oss:${ARTIFACTORY_IMAGE_TAG}
          ports:
            - containerPort: 8081
            - containerPort: 8082
          readinessProbe:
            httpGet:
              path: /artifactory/api/system/ping
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: artifactory-data
              mountPath: /opt/jfrog/artifactory/var

      volumes:
        - name: artifactory-data
          persistentVolumeClaim:
            claimName: ${DEPLOYMENT_PREFIX}-artifactory-pvc
        - name: artifactory-config
          configMap:
            name: ${DEPLOYMENT_PREFIX}-artifactory-config
            defaultMode: 0666

  - apiVersion: v1
    kind: Service
    metadata:
      name: ${DEPLOYMENT_PREFIX}-artifactory-service
    spec:
      selector:
        app.kubernetes.io/name: ${DEPLOYMENT_PREFIX}-artifactory
      ports:
        - name: http-8081
          port: 8081
          targetPort: 8081
          protocol: TCP
        - name: http-8082
          port: 8082
          targetPort: 8082
          protocol: TCP

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: ${DEPLOYMENT_PREFIX}-artifactory-route
    spec:
      to:
        kind: Service
        name: ${DEPLOYMENT_PREFIX}-artifactory-service
      port:
        targetPort: http-8082

parameters:
  - name: DEPLOYMENT_PREFIX
    description: Unique deployment prefix
    required: true

  - name: ACTIVE_DEADLINE_SECONDS
    description: Active deadline seconds
    required: true

  - name: ARTIFACTORY_IMAGE_TAG
    description: Artifactory image tag
    required: true

  - name: POSTGRES_DB
    description: Database name
    required: true

  - name: POSTGRES_USER
    description: Database user
    required: true

  - name: POSTGRES_PASSWORD
    description: Database password
    required: true

  - name: POSTGRES_HOST
    description: Database host
    required: true
