apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: test-artifactory
objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ${DEPLOYMENT_PREFIX}-artifactory-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2.5Gi
      volumeMode: Filesystem

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${DEPLOYMENT_PREFIX}-artifactory-system-yaml
    data:
      system.yaml: |
        shared:
          database:
            type: postgresql
            driver: org.postgresql.Driver
            url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}
            username: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}

  - apiVersion: v1
    kind: Pod
    metadata:
      name: ${DEPLOYMENT_PREFIX}-artifactory
      labels:
        app.kubernetes.io/name: ${DEPLOYMENT_PREFIX}-artifactory
    spec:
      restartPolicy: Never
      activeDeadlineSeconds: ${{ACTIVE_DEADLINE_SECONDS}}

      initContainers:
        - name: setup-system-yaml
          image: releases-docker.jfrog.io/jfrog/artifactory-oss:${ARTIFACTORY_IMAGE_TAG}
          command:
            - sh
            - -c
            - |
              mkdir -p /opt/jfrog/artifactory/var/etc
              cp /tmp/system.yaml /opt/jfrog/artifactory/var/etc/system.yaml
              chmod 666 /opt/jfrog/artifactory/var/etc/system.yaml
          volumeMounts:
            - name: artifactory-data
              mountPath: /opt/jfrog/artifactory/var
            - name: system-yaml
              mountPath: /tmp/system.yaml
              subPath: system.yaml

      containers:
        - name: artifactory
          image: releases-docker.jfrog.io/jfrog/artifactory-oss:${ARTIFACTORY_IMAGE_TAG}
          ports:
            - containerPort: 8081
            - containerPort: 8082
          volumeMounts:
            - name: artifactory-data
              mountPath: /opt/jfrog/artifactory/var

      volumes:
        - name: artifactory-data
          persistentVolumeClaim:
            claimName: ${DEPLOYMENT_PREFIX}-artifactory-pvc
        - name: system-yaml
          configMap:
            name: ${DEPLOYMENT_PREFIX}-artifactory-system-yaml
            defaultMode: 0666

  - apiVersion: v1
    kind: Service
    metadata:
      name: ${DEPLOYMENT_PREFIX}-artifactory-service
    spec:
      ports:
        - name: http-8081
          port: 8081
          targetPort: 8081
          protocol: TCP
        - name: http-8082
          port: 8082
          targetPort: 8082
          protocol: TCP
      selector:
        app.kubernetes.io/name: ${DEPLOYMENT_PREFIX}-artifactory

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: ${DEPLOYMENT_PREFIX}-artifactory-route
    spec:
      port:
        targetPort: 8082
      to:
        kind: Service
        name: ${DEPLOYMENT_PREFIX}-artifactory-service
      tls:
        termination: edge

parameters:
  - description: Unique deployment prefix
    name: DEPLOYMENT_PREFIX
    required: true
  - description: Active deadline seconds
    name: ACTIVE_DEADLINE_SECONDS
    required: true
  - description: Artifactory version
    name: ARTIFACTORY_IMAGE_TAG
    required: true
  - name: POSTGRES_DB
    description: Database name
    required: true
  - name: POSTGRES_USER
    description: Database user
    required: true
  - name: POSTGRES_PASSWORD
    description: Database password
    required: true
  - name: POSTGRES_HOST
    required: true