apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: test-postgres
objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ${DEPLOYMENT_PREFIX}-${POSTGRES_NAME}-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: ${POSTGRES_STORAGE}
      volumeMode: Filesystem
  - apiVersion: v1
    kind: Pod
    metadata:
      name: ${DEPLOYMENT_PREFIX}-${POSTGRES_NAME}
      labels:
        app.kubernetes.io/name: ${DEPLOYMENT_PREFIX}-${POSTGRES_NAME}
    spec:
      restartPolicy: Never
      activeDeadlineSeconds: ${{ACTIVE_DEADLINE_SECONDS}}
      containers:
        - name: postgres
          image: ${DOCKER_REGISTRY}/postgres:${POSTGRES_IMAGE_TAG}
          env:
            - name: POSTGRES_DB
              value: ${POSTGRES_DB}
            - name: POSTGRES_USER
              value: ${POSTGRES_USER}
            - name: POSTGRES_PASSWORD
              value: ${POSTGRES_PASSWORD}
          ports:
            - containerPort: 5432
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U ${POSTGRES_USER}
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: ${DEPLOYMENT_PREFIX}-${POSTGRES_NAME}-pvc

  - apiVersion: v1
    kind: Service
    metadata:
      name: ${DEPLOYMENT_PREFIX}-${POSTGRES_NAME}-service
    spec:
      ports:
        - port: 5432
          targetPort: 5432
      selector:
        app.kubernetes.io/name: ${DEPLOYMENT_PREFIX}-${POSTGRES_NAME}
      type: LoadBalancer

parameters:
  - name: DEPLOYMENT_PREFIX
    description: Unique deployment prefix
    required: true
  - name: POSTGRES_NAME
    description: Logical name of postgres (e.g. artifactory, test, reporting)
    required: true
  - description: Postgres image tag
    name: POSTGRES_IMAGE_TAG
    required: true
  - name: POSTGRES_DB
    description: Database name
    required: true
  - name: POSTGRES_USER
    description: Database user
    required: true
  - name: POSTGRES_PASSWORD
    description: Database password
    required: true
  - name: POSTGRES_STORAGE
    description: PVC storage size
    required: true
    value: 500Mi
  - name: ACTIVE_DEADLINE_SECONDS
    description: Active deadline seconds
    required: true
  - name: DOCKER_REGISTRY
    description: Docker registry
    required: true